### ISSUE TITLE
Glyph Music Visualizer and battery indicator not working.

### ISSUE THREAD

**Issue by reindex-ot** [Fr4nKB/Glyphify#15]
Doesn't seem to work with v1.4

**Comment by Fr4nKB** [comment]
Glyph Music Visualizer is not present in v1.4, will be in v1.4.1
Does Extended Essential work for you? Have you followed the instructions on how to update the app? Did you try uninstalling, reboot and reinstall?

**Comment by reindex-ot** [comment]
v1.4.1 has not been tested because there is no built apk.

The installation process is done in one go.
Visualizer has issues with all Nothing Phones.

**Comment by Fr4nKB** [comment]
I'm sorry, I misunderstood your first post.
Other users have reported this, I'll see what I can do.
The strange thing is that every other NOS glyph feature is compatible with the app...
