### ISSUE TITLE
Number of Zones text is cut off

### ISSUE THREAD

**Issue by reindex-ot** [Fr4nKB/Glyphify#16]
![IMG_20240809_083019](https://github.com/user-attachments/assets/8e013dda-b162-4711-ad51-7b379f213567)
There is an issue where the text in the Glyph Zone is cut off.

`5 個のゾーン` `5 個のゾー...`
`33 個のゾーン` `33 個のゾ...`

**Comment by Fr4nKB** [comment]
The reason is because the button size is fixed, I'll make it expand when needed.
Thanks
