### ISSUE TITLE
Crash when playing a music title

### ISSUE THREAD

**Issue by muhkuhaushonolulu** [Fr4nKB/Glyphify#17]
https://github.com/user-attachments/assets/7ddb6a57-3588-427e-81be-2651cc534ba5

The song plays for 1 or 2 seconds, then the app crashes

**Comment by Fr4nKB** [comment]
Can you send me the file you're using?
Also I have notice that you are seeing the zone selection which shouldn't happen on (2a), I'll fix that too

**Comment by muhkuhaushonolulu** [comment]
[SamsungodeOver.zip](https://github.com/user-attachments/files/16569401/SamsungodeOver.zip)

Here it is. Didnt know that the zone selection shouldnt be visible on 2a. 😅

**Comment by Fr4nKB** [comment]
Yeah, it's only for Phone(2).
I've just realized that I cannot no longer test ringtones made on phone(2a) on my devices because the changes I've made recently, does this happen with every song? Try converting different songs

**Comment by muhkuhaushonolulu** [comment]
Yes, i tried with 2 other files. Same behaviour..

Btw i translated the readme: 
[README_de-1.md](https://github.com/user-attachments/files/16569569/README_de-1.md)

**Comment by Fr4nKB** [comment]
Thanks. I've found the problem, I think is only affecting (2a)s.
I'll release a hotfix in a few hours
