### ISSUE TITLE
Please install Crowdin as your translation environment.

### ISSUE THREAD

**Issue by reindex-ot** [Fr4nKB/Glyphify#19]
Use Crowdin for fast updates, translation corrections, and more.
This will also allow for greater flexibility in terms of language support.
[https://crowdin.com/](https://crowdin.com/)

**Comment by muhkuhaushonolulu** [comment]
Crowdin isn't free anymore (as far as i know)
Maybe there are other services available?

**Comment by reindex-ot** [comment]
Use Weblate.
