### ISSUE TITLE
2a's Battery Indicator Beta Feature

### ISSUE THREAD

**Issue by puhbu** [Fr4nKB/Glyphify#2]
Hello! I saw that you've added that interesting new beta feature in Glyphify! I decided to try it out and even after doing like all of the instructions mentioned there, there still is no battery indiciator while charging.

**Comment by Fr4nKB** [comment]
I'll look into it in the next days, I don't have a Phone(2a) myself so debugging requires more time

**Comment by puhbu** [comment]
Nice, looking forward to it!

**Comment by Fr4nKB** [comment]
New version with fix available, let me know if it works for you
