### ISSUE TITLE
Allow restricted settings Popup Dialog.

### ISSUE THREAD

**Issue by reindex-ot** [Fr4nKB/Glyphify#20]
Dialog to be displayed with instructions on how to disable the Allow restricted settings.

**Comment by muhkuhaushonolulu** [comment]
![Screenshot_20240812-112850.png](https://github.com/user-attachments/assets/7878ded8-c571-4a01-83f3-d8e01d74505a)

I dont have the three dots

**Comment by Fr4nKB** [comment]
That's because you first need to tap the toggle when asked to grant permission, then the three dots will appear.
Makes no sense I know.
