### ISSUE TITLE
Restricted setting warning

### ISSUE THREAD

**Issue by dogukanishere** [Fr4nKB/Glyphify#21]
Hello everyone,

I get this warning when I want to open settings to view remaining battery status on Nothing Phone 2a.

https://drive.google.com/file/d/1eR677PFZ6Cz-85IyvZSTHlcADRRN_ZPd/view?usp=sharing

**Comment by reindex-ot** [comment]
Settings -> App -> Glyphify -> Menu (3dot) -> Allow restricted settings
