### ISSUE TITLE
2a battery indicator doesn't work on Nothing OS 2.6

### ISSUE THREAD

**Issue by Aidam7** [Fr4nKB/Glyphify#34]
When shaking the phone, the shake is, I presume, registered because the notification glyphs light up, however, the charging indicator newer activates.

**Comment by Fr4nKB** [comment]
Due to the migration from Glyphify v1 to v2, the old app won’t work without Glyph debug mode on.
Please turn it on from developer settings.

**Comment by vdnttt** [comment]
i tried turning on the debug mode but it still doesn't work, as soon as i turned the glyph debug mode on it said " **_Glyph Interface debug mode will be enabled for 48 hours_**", after that nothing happens. Essential notifications set for particular app and the charging indicator doesn't work (Device: Nothing Phone 2a)


![Screenshot_20240911-165513](https://github.com/user-attachments/assets/2919dfab-e72d-4feb-909c-a5124c312427)

**Comment by Fr4nKB** [comment]
Yeah glyph debug mode only lasts for 48 hours, it something to leave with for the moment.
Try rebooting or reinstalling the app, I can assure you it works with glyph debug mode on.

**Comment by vdnttt** [comment]
okay it does work after a restart. 
I'll let you know if there're any other issues
~ thanks
