### ISSUE TITLE
Lights do not light

### ISSUE THREAD

**Issue by Fadd0SIMP** [Fr4nKB/Glyphify#35]
Device: Nothing phone 2
Os version: 2.6 September patch
Glyphify version: 1.4.2
All requirements like notification access etc. are met and turned on but glyphs don't react on app notifications 
Tried turning on the glyph debug mode, reinstalling Glyphify and rebooting, still not working

**Comment by hujuDev** [comment]
Same here. Everything worked great before the latest update, but since then, the extended essential notifications aren't working. Love that feature, so a fix would be greatly appreciated!

**Comment by Fr4nKB** [comment]
Try this and follow the order:
1. Uninstall the app
2. Turn ON glyph debug mode
3. Reboot
4. Ensure glyph debug mode is still on and reinstall

Keep in mind glyph debug mode needs to stay on and it resets after 48 hours. Unfortunately Glyph SDK is bugged and can't pass from non-debugging mode to debugging mode smoothly

**Comment by hujuDev** [comment]
I saw in the other thread to reboot after turning on glyph debugging mode and that worked even without reinstalling.

Is there a fix in the pipeline that doesn't require glyph debugging mode for version 2.0?

Anyway, thanks for the great work! This app turned Glyphs from a gimmick to a really useful feature for me, so I'm really grateful for everything you do!

**Comment by Fr4nKB** [comment]
v2.0 won't need glyph debug mode, the reason why v1 needs it is because the signature used to register with Nothing GDK has changed during the migration.

I'm glad you find it useful. v2.0 will release next week if everything goes well so I hope to see you there!

I'll close this issue now
