### ISSUE TITLE
nothing 2a plus

### ISSUE THREAD

**Issue by Shatakiii** [Fr4nKB/Glyphify#36]
![Screenshot_20240917-023534](https://github.com/user-attachments/assets/91e9ee17-ade9-4bd2-839c-c8c1039ecfbf)
it's not working on my nothing phone 2a plus doesn't show charging animation and when i convert the audio it gives me a glitchy broken glyph light and is not working when i try to play it it crashes the app can you please help me with these issues

**Comment by Fr4nKB** [comment]
2a plus is not supported in this release but will be in v2 once it's out

**Comment by Shatakiii** [comment]
> 2a plus is not supported in this release but will be in v2 once it's out

how much time will it take for v2?
