### ISSUE TITLE
No Glyph use at all

### ISSUE THREAD

**Issue by Dhbdndjdjrndnd** [Fr4nKB/Glyphify#38]
On my np2 there is literally no use of any gliph even after allowing to read all notifications.

Any ideas where the problem could be?

**Comment by Dhbdndjdjrndnd** [comment]
I managed to get the app working after a force stop.

For some reason I need to force the app to stop to adapt so any change

**Comment by Fr4nKB** [comment]
First of all, do you have glyph debug mode on?

Note that v1.4.2 doesn't apply changes in real time: if you've set a mapping for glyph x and animation y, once you receive the notification it should work as expected but if you try to change the animation/mapping while the notification is still on then changes won't take place unless you restart the app.

More specifically, you'll get a bug in which, by removing/tapping the notification, the old animation will keep being displayed and the only thing you can do is restart the app.

This bug, of course, was solved in v2.0.
Hope it helps

**Comment by Dhbdndjdjrndnd** [comment]
Yeah I have glzph debug enabled. 


Thanks for explaining.

When could we expect to see V2?

**Comment by Fr4nKB** [comment]
Very very soon😉
