### ISSUE TITLE
Indian Nothing Phone (2) unsupported

### ISSUE THREAD

**Issue by SebiAi** [Fr4nKB/Glyphify#4]
The Indian version of the Nothing Phone (2) has a different model string.
Normal: `A065`
Indian: `AIN065`

This difference just popped into my head when I read through the `Constants.kt` file for the #3 issue - I do not have an Indian Phone (2) for testing.

Source:
Decompiled source from the Nothing [Glyph-Developer-Kit](https://github.com/Nothing-Developer-Programme/Glyph-Developer-Kit) (KetchumSDK_Community_20240307.jar):
```Java
// Decompiled Glyph class excerpt
public class Glyph {
    // ...
    static String DEVICE_22111 = "A065";
    static String DEVICE_22111I = "AIN065";
    // ...
}

// Decompiled Phone (2) check in Common class
public static boolean is22111() {
    if (Glyph.DEVICE_22111.equals(Build.MODEL) || Glyph.DEVICE_22111I.equals(Build.MODEL)) {
        return true;
    }
    return false;
}
```

**Comment by Fr4nKB** [comment]
Interesting, I had no idea that was a thing.
Thank you
