### ISSUE TITLE
2a plus

### ISSUE THREAD

**Issue by Shatakiii** [Fr4nKB/Glyphify#44]
i had tried downloading this app before it was not compatible with my phone 2a plus so i refunded it i deleted it but today i wanted to check if its compatible with my 2a plus but it was not and now i can't refund it anymore

**Comment by Fr4nKB** [comment]
This is not the place for this type of inquiries.
Send an email at glyphify.help@gmail.com with your order id.
Also note that I'll update the Play Store's description once the app supports (2a) Plus.
