### ISSUE TITLE
Cannot turn on notification access to NP2

### ISSUE THREAD

**Issue by sinhaaritro** [Fr4nKB/Glyphify#6]
I cannot turn on device and notifications access on NP2. 

![Screenshot_20240721-133833](https://github.com/user-attachments/assets/f623e134-ad49-470e-bbe6-b0987abe468a)
![Screenshot_20240721-133234](https://github.com/user-attachments/assets/172aaa86-1b14-4f58-97c1-7dce6b84c306)

**Comment by ProgettiPascon** [comment]
Had the same problem yesterday. 
If you go in `Settings` -> `Apps` -> `Glyphify `-> `Permissions`, by clicking on the three dots in the up-right corner, you can allow the access to restricted settings.
