### ISSUE TITLE
Ringtones make app crash on nothing phone 1

### ISSUE THREAD

**Issue by misiek998** [Fr4nKB/Glyphify#8]
Option ringtones makes app crash every time when pressed.
[2024-07-27_08.05.zip](https://github.com/user-attachments/files/16398437/2024-07-27_08.05.zip)
I dont knows how to read this, but maby help you :)

**Comment by Fr4nKB** [comment]
Which option? Any of the three?

**Comment by misiek998** [comment]
![Screenshot_20240728-140545~2](https://github.com/user-attachments/assets/88c35e6a-6dcb-49aa-9f71-dbfb7065b77c)

**Comment by misiek998** [comment]
Update: app crash because no Item on the list. After generating one or more ringtones app stop crashing

**Comment by Fr4nKB** [comment]
Ok, maybe I know what to look for now. I'll let you know

**Comment by Fr4nKB** [comment]
Fixed, will ship in next version. Thanks!
