### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by MemeCornucopia** [Fr4nKB/Glyphify#9]
For the essential notification extended thing allow us to pick certain notifications types like the actual essential notification thing does. And ofc convos.

**Comment by Fr4nKB** [comment]
AFAIK this cannot be done with a third party app (Android doens't let you access user conversations for privacy reasons), you would need to implement this in the Nothing OS.

**Comment by JLhfbr** [comment]
![Screenshot_20241008-112117](https://github.com/user-attachments/assets/b1c9a477-6720-4344-8966-d3db2fed9e5f)
In my Case Coversations is granted over settings
